/* automatically generated by rust-bindgen 0.59.1 */
/* then edited down to a fairly small selection */
use libc::size_t;

extern "C" {
    pub fn radamsa_init();
}
extern "C" {
    pub fn radamsa(
        ptr: *const u8,
        len: size_t,
        target: *mut u8,
        max: size_t,
        seed: ::std::os::raw::c_uint,
    ) -> size_t;
}
extern "C" {
    pub fn radamsa_inplace(
        ptr: *mut u8,
        len: size_t,
        max: size_t,
        seed: ::std::os::raw::c_uint,
    ) -> size_t;
}
